redhat-developer/design-manual

- gulpfile.js
Update `gulpfile.js` function to prepend `bundle exec` to the production level jekyll serve commands.
> Update Gulpfile 03/19/2020

- pages/portal.md
Add the Admin console as an `<iframe>` in order to bypass some of the authentication errors due to host resolution.
> Add an Admin Portal page

- .gitignore
- admin/config.yml
- docs/admin/config.yml
- Update configurations for the Admin UI to automatically populate the beginnings of file paths.
- Update `.gitignore` to ignore local VSCode launch settings.
- Update the developers.redhat.com submodule.
> Config updates

- admin/config.yml
- Rearrange the Collections to match the site navigation and setup.
- Add a Collection option for layout examples.
> Update admin ui config

- .github/labeler.yml
- .github/pull_request_template.md
- .github/workflows/automerge.yml
- .github/workflows/label.yml
- package.json
- Update the `labeler.yml` file to fix missing labels, add new labels and reorganize what is cross referenced
- Add an `automerge.yml` configuration file to handle PRs and merging them once a given set of criteria are met
> Update GitHub Action configurations

- .github/workflows/automerge.yml
- .github/workflows/github-tag-actions.yml
- package-lock.json
- package.json
- Update the automerge GitHub Action to squash commits
- Update the release GitHub Action to update the changelog as part of the release process
> Update GitHub Actions

- .github/workflows/automerge.yml
- .github/workflows/github-tag-actions.yml
- .travis.yml
- CHANGELOG.md
* Update the `.travis.yml` configuration to automatically update the `Changelog.md` file
* Update`.travis.yml` to bump the version number and create a new tag after a successful deployment
* Change automerge github action commit message
> Update Travis and GitHub build scripts

- .github/workflows/automerge.yml
- .travis.yml
- README.md
- guides/BUILD_CONFIG.md
- scripts/release.sh
* Add the GitHub Actions labels to the `Readme.md` file
* Update `.travis.yml` to reference GitHub tags
> Travis builds

- .github/pull_request_template.md
- .gitignore
- CHANGELOG.md
- _config.yml
- _data/getting-started.yml
- _sass/main.scss
- gulpfile.js
- netlify.toml
- package-lock.json
- package.json
- scripts/release.sh
- styles/main.scss
* Update `Changelog.md`
* Bump version in `package.json` and `package-lock.json` files
* Simplify PR templates
* Cleanup code comments and unused bits of code
> Code Cleanup and updates

- CHANGELOG.md
- _config.yml
- _includes/head.html
- _includes/header.html
- _layouts/search.html
- assets/js/search.js
- guides/SETUP.md
- gulpfile.js
- package-lock.json
- package.json
- pages/components/card-grid/card-grid.md
- pages/search.md
- sitemap.xml
- styles/partials/_search.scss
- styles/utilities/_color-scheme.scss
* Move Search to a single page, rather than an input box that drops you to a separate page
* Improve search results to include keywords within titles and pages
* Configure Search to refresh upon each key press (per letter search)
* Results displayed and updated as user types
> feat: Search Improvements

- _layouts/portal.html
- pages/portal.md
* Fix rendering of the portal layout
> fix: Update portal screen

- .github/workflows/automerge.yml
- .github/workflows/bump-tag-version.yml
Create a new file `bump-tag-version.yml` as a GitHub Action workflow for automatically bumping the repo tags.
> Create tag bumping action

- _config.yml
- package-lock.json
- package.json
- Upgrade Node to `12.18.1`, which is the LTS version
- Upgrade NPM to `6.14.5`
> Upgrade Node version to 12

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/security-report.md
Add a Security report, which will be linked from the `Security.md` file.
Add a Bug report template.
> Update issue templates

- .github/ISSUE_TEMPLATE/general-questions.md
Create a General Questions issue template to replace the blank issue.
> Create a General Questions issue template

- .github/ISSUE_TEMPLATE/config.yml
Create a configuration file (`config.yml`) for issues.
> Create issue configuration file

- _includes/footer.html
- styles/partials/_footer.scss
- Update the footer sizing and content
- Add 'Deploys by Netlify' information to the footer
> Update footer styling and info

- .github/workflows/bump-tag-version.yml
- _config.yml
- package-lock.json
- package.json
- Update the GitHub Action for bumping tag version to include updating the Changelog and the Release version
- Update version number for `package.json`, `package-lock.json`, and `_config.yml`
> Update GitHub action for tags

- _config.yml
- package-lock.json
- package.json
- pages/components/curated-events/curated-events.md
- pages/components/curated-events/default.md
Fix https://github.com/redhat-developer/design-manual/runs/890432416
> GitHub Pages failed to build your site.
> A file was included in `pages/components/curated-events/default.md` that is a symlink or does not exist in your `_includes` directory.
> Patch Curated Events component example

- .github/workflows/bump-tag-version.yml
- _config.yml
- package-lock.json
- package.json
Update the **Bump tag version** GitHub Action to use the references from the generated changeling to create release notes for each release.
> fix: GitHub Changelog generator action

- admin/config.yml
Remove commas from config file that were causing errors.
> patch: Update config.yml

- styles/partials/_background.scss
Fix image path for background images on the homepage.
fixes https://github.com/redhat-developer/design-manual/issues/164
> fix: missing background images

- admin/config.yml
Update the Netlify CMS to use the correct commit message syntax for the automated release action to update release notes properly.
fixes https://github.com/redhat-developer/design-manual/issues/168
> fix: Update commit messages for Netlify CMS

- .github/release-drafter.yml
Update `release-drafter` action to include Netlify CMS labels.
> fix: Update release-drafter.yml

- pages/assemblies/expandable-product-groups.md
- pages/assemblies/featured-articles.md
- pages/assemblies/featured-evangelists.md
- pages/assemblies/featured-resources.md
- pages/assemblies/image-hero.md
- pages/assemblies/katacodas.md
- pages/assemblies/learning-guides.md
- pages/assemblies/node-reference.md
- pages/assemblies/on-page-navigation.md
- pages/assemblies/product-download-hero.md
- pages/assemblies/product-download-list.md
- pages/assemblies/product-try-it-hero.md
- pages/assemblies/rich-text-columns.md
- pages/assemblies/rich-text-with-image.md
- pages/assemblies/rich-text.md
- pages/assemblies/sign-up-hero.md
- pages/assemblies/static-item.md
- pages/assemblies/video-hero.md
- pages/assemblies/videos.md
- pages/assemblies/wordpress-post-reference.md
Move various Assemblies under the correct navigation (Create) vs Develop.
> fix: place assemblies under correct nav

- _layouts/assemblies.html
- _layouts/create.html
- admin/config.yml
- admin/index.html
- pages/assemblies/assembly-template.md
- pages/assemblies/curated-links.md
Continued updates of the Assembly page template, which include the following:
- Cleaner YouTube embedding at the top of the page (remove from `body` input field into it's own FrontMatter).
- Update `featured_image` field to display correctly based on environment.
> fix: Update Assembly page template

- .github/CODEOWNERS
Create a file informing users who the 'Codeowners' are for the repo.
> fix: create a CODEOWNERS file

- admin/index.html
Add the Netlify identity widget to the site in order to use username/password authentication.
> fix: add Netlify identity

- .github/workflows/codeql-analysis.yml
Enable code scanning of JS files.
> fix: Create codeql-analysis.yml

- _config.yml
- guides/SETUP.md
- package-lock.json
- package.json
Update the Node environment to the latest TLS version (12.18.4).
> fix: update to Node LTS 12.18.4

- pages/create/articles-full.md
- styles/custom/articles.scss
Update the Article example to include an article outline sidebar.
> fix: add Article Outline slideout

- .github/workflows/release-drafter.yml
Update the `release-drafter.yml` file to automatically publish the drafted release once a PR is merged.
> patch: update release-drafter action

- .github/workflows/jekyll.yml
- .github/workflows/site-build.yml
- _includes/sidenavs/develop.html
Fix the incorrect link where 'Develop' in the vertical nav links to the 'Design' page.
> fix: incorrect link

- pages/components/trending-nav/default.md
- pages/components/trending-nav/template.md
- styles/custom/trending-nav.scss
Update the Trending Nav component example to match the latest design iteration for an initial release. Simplify page to show fewer examples, focusing on the initial release, with others referred to as 'Advanced'.
> fix: Update trending nav
