- .travis.yml
Update the Travis-CI configuration to use the `local_dir: docs` option, so that the content of `docs/` is what is used for the **gh-pages** branch and deployment.
> Update Travis local_dir config

- pages/assemblies/call-to-action.md
- pages/assemblies/collection.md
- pages/assemblies/combo.md
- pages/assemblies/content-call-to-action-1.md
- pages/assemblies/content-call-to-action.md
- pages/assemblies/content-pull-quote.md
- pages/assemblies/content.md
- pages/assemblies/cta-form.md
- pages/assemblies/curated-content.md
- pages/assemblies/curated-links.md
- pages/assemblies/curated-products.md
- pages/assemblies/dynamic-content-list.md
- pages/assemblies/dynamic-content.md
- pages/assemblies/eloqua-form-embed.md
- pages/assemblies/events-hero.md
- pages/assemblies/events-list.md
- pages/assemblies/expandable-product-groups.md
- pages/assemblies/featured-articles.md
- pages/assemblies/featured-evangelists.md
- pages/assemblies/featured-resources.md
Remove the indentations of the embedded images that were causing them to be part of the ordered lists.
This also fixes the issue where the images were not rendering in the Admin UI.
> Fix embedded image indentation

- admin/config.yml
Add file type to the Netlify commit messages to distinguish between navigations and pages.
`type: "navigation"` or `type: "page"`
> Add file type to Netlify CMS commit messages

- .travis.yml
- admin/config.yml
- scripts/publish.sh
- scripts/release.sh
After renaming the `Master` branch to `Main`, the various scripts also needed to be updated. All references to `Master` have been replaced with `Main`
> Rename references of Master to Main

- _includes/header.html
- assets/js/site.js
- styles/partials/_navigation.scss
* Add the menu button for opening/closing the vertical navigation on mobile
* Set vertical navigation to appear from the bottom of the screen when opened
> Update vertical nav on mobile

- .github/workflows/automerge.yml
Update the `automerge.yml` GitHub Action to include a step for automatically creating a new tag. This will then start up the `Create release` action, bumping the release number.
> fix: add automated tag creation

- .travis.yml
Set Travis-CI to only build the `main` and `gh-pages` branches, rather than all branches that are pushed to the repo.
**Reference:** https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
> Set branch builds

- .github/workflows/gulp-build.yml
- .github/workflows/site-build.yml
- package-lock.json
- package.json
Start the process of moving build scripts from Travis-CI to GitHub Actions.
- Configure a `gulp-build.yml` file to execute NPM scripts on pull requests
- Remove branch and pull request builds from the Travis-CI process
> fix: Start moving build scripts to Github Actions

- netlify.toml
Set the `deploy-preview` Netlify build to use the production environment configuration in order to render the site without the `/design-manual` path.
> Set deploy-preview to use production environment

- pages/components/tables/template.md
Remove the `<blockquotes>` from the Tables page, as they were being rendered using the `rhdp.css` styles.
fixes https://github.com/redhat-developer/design-manual/issues/163
> fix: blockquotes on Tables page

- _layouts/assemblies.html
- admin/config.yml
- admin/index.html
- pages/assemblies/curated-links.md
- styles/custom/assemblies.scss
Update the Assembly creation template in the CMS with the following changes:
- Set "Intro Paragraph" to be a plain text field. This will prevent code from being added to the frontmatter, which could break the site.
- Add a field input hint to the "Body" for embedding YouTube videos.
- Add a YouTube embed ability to the "Body", requiring only a link, rather than the entire `<iframe>` code.
- Add a new label dropdown for letting users know where they can find the examples in the Drupal environment.
> fix: Update Assembly creation template

- admin/config.yml
Add multi-column layout options for Assembly example pages using the `object` widget in the CMS.
> fix: Add multi-column layout for Assembly examples

- admin/config.yml
- pages/assemblies/curated-links.md
Simplify the **Featured Video** and **Featured Image** uploads from objects to strings in order to prevent indentation in the FrontMatter.
> fix: simplify video and image uploads for Assembly examples

- _layouts/assemblies.html
- _layouts/create.html
- pages/assemblies/curated-links.md
- Move the **Featured Image** field to the bottom of the page.
- Delete the Featured Image from the _Curated Links_ page.
> fix: placement of featured image

- _layouts/assemblies.html
- _layouts/create.html
- admin/admin.css
- admin/index.html
- pages/assemblies/curated-links.md
- Remove the duplicate `video-title` from page frontmatter, which resulted in rendering errors.
- Clean up **curated-links** page so that frontmatter config matches the `.yml` template.
- Remove `featured-image` and `featured-image_title` front available configuration options.
> fix: remove duplicate widget variables

- admin/config.yml
- admin/index.html
Change the CMS backend from `git-gateway` to `github` and enable **Open Authoring** in order to accept contributions (PRs) from those outside of the org.
> fix: change backend auth from git-gateway to github

- _data/components.yml
- pages/components/topic-nav/default.md
- pages/components/topic-nav/template.md
- styles/custom/topic-nav.scss
Add an example of the new Topic Navigation, to be used in conjunction with the updated universal navigation.
This new component page includes multiple CodePens, allowing for examples to be updated without updating the site.
fixes issue #196
> fix: Add Topic Nav component example

- pages/components/tables/template.md
- styles/custom/tables.scss
Move the example CSS for the Tables component to it's own CSS file (was inline). This will allow for easier cleanup/maintenance in the future, once Tables are a part of the Developer site's core styling.
> fix: move Tables example CSS to separate file

- .github/ISSUE_TEMPLATE/security-report.md
- .github/labeler.yml
- guides/BUILD_CONFIG.md
- guides/DEFAULT_FRONTMATTER.md
- guides/DEVELOPMENT.MD
- guides/GETTING-STARTED.MD
- guides/LABELS.md
Update documentation for the site. Includes notes on NodeJS LTS version bump, updates for Labeler, cleanup of the `build_config.md` file, expanded upon default Frontmatter configs per sections of the site, and more.
> fix: documentation updates

- _config.yml
- _includes/head.html
- Simplify the meta description to either include the general site description or the introductory paragraph for a page.
- If there is no introductory paragraph, the general site description will be used.
fixes #209
> fix: simplify meta descriptions

- _data/design.yml
- brand-assets/RHD_Full_Logo/full-logo.md
- pages/design/color-palette.md
- Improve the **Logos** page (formerly **Full Logos**) layout with updated table layout
- Change the name of the page from **Full Logos** to **Logos** to better represent the page content
> fix: Update logo reference page
